FileNotFoundError in line 46 of /home/jpmcgeown/github/fmri_workflow/Snakefile:
[Errno 2] No such file or directory: 'scan_list.csv'
  File "/home/jpmcgeown/github/fmri_workflow/Snakefile", line 46, in <module>
  File "/home/jpmcgeown/miniconda3/envs/snake/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
  File "/home/jpmcgeown/miniconda3/envs/snake/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
  File "/home/jpmcgeown/miniconda3/envs/snake/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 482, in _read
  File "/home/jpmcgeown/miniconda3/envs/snake/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
  File "/home/jpmcgeown/miniconda3/envs/snake/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
  File "/home/jpmcgeown/miniconda3/envs/snake/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
  File "/home/jpmcgeown/miniconda3/envs/snake/lib/python3.8/site-packages/pandas/io/parsers/base_parser.py", line 222, in _open_handles
  File "/home/jpmcgeown/miniconda3/envs/snake/lib/python3.8/site-packages/pandas/io/common.py", line 702, in get_handle
