Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 8
Rules claiming more threads will be scaled down.
Provided resources: mem_mb=25000, mem_mib=23842, disk_mb=1000, disk_mib=954, cpus=8, time_min=180, gpu=0
Select jobs to execute...

[Wed Mar 29 12:41:55 2023]
rule fmriprep:
    input: /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_long/bids/sub-rugby1/ses-a, /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_long/bids/sub-rugby1/ses-b, /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_long/bids/derivatives/freesurfer_agg/sub-rugby1
    output: /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_long/bids/derivatives/fmriprep/sub-rugby1, /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_long/bids/derivatives/fmriprep/sub-rugby1.html
    jobid: 0
    reason: Missing output files: /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_long/bids/derivatives/fmriprep/sub-rugby1, /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_long/bids/derivatives/fmriprep/sub-rugby1.html
    wildcards: resultsdir=/nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_long, subject=rugby1
    threads: 8
    resources: mem_mb=25000, mem_mib=23842, disk_mb=1000, disk_mib=954, tmpdir=/dev/shm/jobs/33757298, cpus=8, time_min=180, gpu=0

fmriprep /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_long/bids /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_long/bids/derivatives/fmriprep participant --participant-label rugby1 --skip-bids-validation --md-only-boilerplate --fs-subjects-dir /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_long/bids/derivatives/freesurfer_agg --output-spaces MNI152NLin2009cAsym:res-2 --stop-on-first-crash --low-mem --mem-mb 25000 --nprocs 8 -w /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_long/work --fs-license-file ./license.txt
Activating singularity image /scale_wlg_persistent/filesets/project/uoa03264/fmri_workflow/.snakemake/singularity/8ba2e11db7a36df6ed76807c131c9dc5.simg
You are using fMRIPrep-22.0.2, and a newer version of fMRIPrep is available: 23.0.1.
Please check out our documentation about how and when to upgrade:
https://fmriprep.readthedocs.io/en/latest/faq.html#upgrading
230328-23:42:19,73 nipype.workflow IMPORTANT:
	 Running fMRIPrep version 22.0.2

         License NOTICE ##################################################
         fMRIPrep 22.0.2
         Copyright 2022 The NiPreps Developers.
         
         This product includes software developed by
         the NiPreps Community (https://nipreps.org/).
         
         Portions of this software were developed at the Department of
         Psychology at Stanford University, Stanford, CA, US.
         
         This software redistributes the versioneer Python package, which is
         Public domain source code.
         
         This software is also distributed as a Docker container image.
         The bootstraping file for the image ("Dockerfile") is licensed
         under the MIT License.
         
         This software may be distributed through an add-on package called
         "Docker Wrapper" that is under the BSD 3-clause License.
         #################################################################
230328-23:42:19,75 nipype.workflow WARNING:
	 Previous output generated by version 0+unknown found.
230328-23:42:19,129 nipype.workflow IMPORTANT:
	 Building fMRIPrep's workflow:
           * BIDS dataset path: /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_long/bids.
           * Participant list: ['rugby1'].
           * Run identifier: 20230328-234200_909c5b93-e854-4c0d-82db-0d0db62be2d1.
           * Output spaces: MNI152NLin2009cAsym:res-2.
           * Pre-run FreeSurfer's SUBJECTS_DIR: /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_long/bids/derivatives/freesurfer_agg.
230328-23:42:21,290 nipype.workflow INFO:
	 No single-band-reference found for sub-rugby1_ses-a_task-rest_run-001_bold.nii.gz.
230328-23:42:21,437 nipype.workflow IMPORTANT:
	 BOLD series will be slice-timing corrected to an offset of 0.721s.
230328-23:42:21,751 nipype.workflow INFO:
	 No single-band-reference found for sub-rugby1_ses-b_task-rest_run-001_bold.nii.gz.
230328-23:42:25,921 nipype.workflow INFO:
	 fMRIPrep workflow graph with 585 nodes built successfully.
230328-23:42:42,668 nipype.workflow IMPORTANT:
	 fMRIPrep started!
230328-23:42:54,857 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_22_0_wf.single_subject_rugby1_wf.anat_preproc_wf.fs_isrunning" in "/nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_long/work/fmriprep_22_0_wf/single_subject_rugby1_wf/anat_preproc_wf/fs_isrunning".
230328-23:42:54,859 nipype.workflow INFO:
	 [Node] Outdated cache found for "fmriprep_22_0_wf.single_subject_rugby1_wf.anat_preproc_wf.fs_isrunning".
230328-23:42:54,877 nipype.workflow INFO:
	 [Node] Executing "fs_isrunning" <nipype.interfaces.utility.wrappers.Function>
230328-23:42:54,885 nipype.workflow INFO:
	 [Node] Finished "fs_isrunning", elapsed time 0.001542s.
230328-23:43:29,330 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_22_0_wf.single_subject_rugby1_wf.anat_preproc_wf.surface_recon_wf.autorecon1" in "/nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_long/work/fmriprep_22_0_wf/single_subject_rugby1_wf/anat_preproc_wf/surface_recon_wf/autorecon1".
230328-23:43:29,332 nipype.workflow INFO:
	 [Node] Outdated cache found for "fmriprep_22_0_wf.single_subject_rugby1_wf.anat_preproc_wf.surface_recon_wf.autorecon1".
230328-23:43:29,355 nipype.workflow INFO:
	 [Node] Executing "autorecon1" <smriprep.interfaces.freesurfer.ReconAll>
230328-23:43:29,357 nipype.interface INFO:
	 recon-all complete : Not running
230328-23:43:29,358 nipype.interface INFO:
	 recon-all complete : Not running
230328-23:43:29,456 nipype.workflow INFO:
	 [Node] Finished "autorecon1", elapsed time 0.099215s.
230328-23:43:32,459 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_22_0_wf.single_subject_rugby1_wf.anat_preproc_wf.surface_recon_wf.fsnative2t1w_xfm" in "/nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_long/work/fmriprep_22_0_wf/single_subject_rugby1_wf/anat_preproc_wf/surface_recon_wf/fsnative2t1w_xfm".
230328-23:43:32,460 nipype.workflow INFO:
	 [Node] Outdated cache found for "fmriprep_22_0_wf.single_subject_rugby1_wf.anat_preproc_wf.surface_recon_wf.fsnative2t1w_xfm".
230328-23:43:32,490 nipype.workflow INFO:
	 [Node] Executing "fsnative2t1w_xfm" <niworkflows.interfaces.freesurfer.PatchedRobustRegister>
230328-23:43:51,943 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_22_0_wf.single_subject_rugby1_wf.anat_preproc_wf.brain_extraction_wf.atropos_wf.01_atropos" in "/nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_long/work/fmriprep_22_0_wf/single_subject_rugby1_wf/anat_preproc_wf/brain_extraction_wf/atropos_wf/01_atropos".
230328-23:43:51,975 nipype.workflow INFO:
	 [Node] Executing "01_atropos" <nipype.interfaces.ants.segmentation.Atropos>
230328-23:44:30,986 nipype.workflow INFO:
	 [Node] Finished "fsnative2t1w_xfm", elapsed time 58.495147s.
230328-23:44:31,569 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_22_0_wf.single_subject_rugby1_wf.anat_preproc_wf.surface_recon_wf.t1w2fsnative_xfm" in "/nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_long/work/fmriprep_22_0_wf/single_subject_rugby1_wf/anat_preproc_wf/surface_recon_wf/t1w2fsnative_xfm".
230328-23:44:31,570 nipype.workflow INFO:
	 [Node] Outdated cache found for "fmriprep_22_0_wf.single_subject_rugby1_wf.anat_preproc_wf.surface_recon_wf.t1w2fsnative_xfm".
230328-23:44:31,603 nipype.workflow INFO:
	 [Node] Executing "t1w2fsnative_xfm" <niworkflows.interfaces.freesurfer.PatchedLTAConvert>
230328-23:44:31,713 nipype.workflow INFO:
	 [Node] Finished "t1w2fsnative_xfm", elapsed time 0.107673s.
230328-23:49:46,81 nipype.workflow WARNING:
	 Error while checking node hash, forcing re-run. Although this error may not prevent the workflow from running, it could indicate a major problem. Please report a new issue at https://github.com/nipy/nipype/issues adding the following information:

	Node: fmriprep_22_0_wf.single_subject_rugby1_wf.func_preproc_ses_a_task_rest_run_001_wf.bold_bold_trans_wf.merge
	Interface: niworkflows.interfaces.nilearn.Merge
	Traceback:
Traceback (most recent call last):

  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/plugins/base.py", line 364, in _local_hash_check
    cached, updated = self.procs[jobid].is_cached()

  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 342, in is_cached
    hashed_inputs, hashvalue = self._get_hashval()

  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 548, in _get_hashval
    self._get_inputs()

  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 619, in _get_inputs
    self.set_input(key, deepcopy(output_value))

  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 312, in set_input
    setattr(self.inputs, parameter, deepcopy(val))

  File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/traits_extension.py", line 330, in validate
    value = super(File, self).validate(objekt, name, value, return_pathlike=True)

  File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/traits_extension.py", line 135, in validate
    self.error(objekt, name, str(value))

  File "/opt/conda/lib/python3.9/site-packages/traits/base_trait_handler.py", line 74, in error
    raise TraitError(

traits.trait_errors.TraitError: The 'header_source' trait of a _MergeInputSpec instance must be a pathlike object or string representing an existing file, but a value of '/nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_long/bids/sub-rugby1/ses-a/func/sub-rugby1_ses-a_task-rest_run-001_bold.nii.gz' <class 'str'> was specified.

Error setting node input:
Node: merge
input: header_source
results_file: /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_long/work/fmriprep_22_0_wf/single_subject_rugby1_wf/func_preproc_ses_a_task_rest_run_001_wf/bold_source/result_bold_source.pklz
value: /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_long/bids/sub-rugby1/ses-a/func/sub-rugby1_ses-a_task-rest_run-001_bold.nii.gz

230328-23:49:46,412 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_22_0_wf.single_subject_rugby1_wf.func_preproc_ses_a_task_rest_run_001_wf.bold_bold_trans_wf.merge" in "/nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_long/work/fmriprep_22_0_wf/single_subject_rugby1_wf/func_preproc_ses_a_task_rest_run_001_wf/bold_bold_trans_wf/merge".
230328-23:49:47,761 nipype.workflow ERROR:
	 Node merge failed to run on host wmc006.
230328-23:49:47,772 nipype.workflow ERROR:
	 Saving crash info to /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_long/bids/derivatives/fmriprep/sub-rugby1/log/20230328-234200_909c5b93-e854-4c0d-82db-0d0db62be2d1/crash-20230328-234947-jmcg465-merge-eb95f4b9-79a1-405c-8f54-54d983ea86d2.txt
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 454, in run
    cached, updated = self.is_cached()
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 342, in is_cached
    hashed_inputs, hashvalue = self._get_hashval()
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 548, in _get_hashval
    self._get_inputs()
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 619, in _get_inputs
    self.set_input(key, deepcopy(output_value))
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 312, in set_input
    setattr(self.inputs, parameter, deepcopy(val))
  File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/traits_extension.py", line 330, in validate
    value = super(File, self).validate(objekt, name, value, return_pathlike=True)
  File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/traits_extension.py", line 135, in validate
    self.error(objekt, name, str(value))
  File "/opt/conda/lib/python3.9/site-packages/traits/base_trait_handler.py", line 74, in error
    raise TraitError(
traits.trait_errors.TraitError: The 'header_source' trait of a _MergeInputSpec instance must be a pathlike object or string representing an existing file, but a value of '/nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_long/bids/sub-rugby1/ses-a/func/sub-rugby1_ses-a_task-rest_run-001_bold.nii.gz' <class 'str'> was specified.

Error setting node input:
Node: merge
input: header_source
results_file: /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_long/work/fmriprep_22_0_wf/single_subject_rugby1_wf/func_preproc_ses_a_task_rest_run_001_wf/bold_source/result_bold_source.pklz
value: /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_long/bids/sub-rugby1/ses-a/func/sub-rugby1_ses-a_task-rest_run-001_bold.nii.gz

230328-23:49:47,794 nipype.workflow CRITICAL:
	 fMRIPrep failed: Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 454, in run
    cached, updated = self.is_cached()
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 342, in is_cached
    hashed_inputs, hashvalue = self._get_hashval()
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 548, in _get_hashval
    self._get_inputs()
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 619, in _get_inputs
    self.set_input(key, deepcopy(output_value))
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 312, in set_input
    setattr(self.inputs, parameter, deepcopy(val))
  File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/traits_extension.py", line 330, in validate
    value = super(File, self).validate(objekt, name, value, return_pathlike=True)
  File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/traits_extension.py", line 135, in validate
    self.error(objekt, name, str(value))
  File "/opt/conda/lib/python3.9/site-packages/traits/base_trait_handler.py", line 74, in error
    raise TraitError(
traits.trait_errors.TraitError: The 'header_source' trait of a _MergeInputSpec instance must be a pathlike object or string representing an existing file, but a value of '/nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_long/bids/sub-rugby1/ses-a/func/sub-rugby1_ses-a_task-rest_run-001_bold.nii.gz' <class 'str'> was specified.

Error setting node input:
Node: merge
input: header_source
results_file: /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_long/work/fmriprep_22_0_wf/single_subject_rugby1_wf/func_preproc_ses_a_task_rest_run_001_wf/bold_source/result_bold_source.pklz
value: /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_long/bids/sub-rugby1/ses-a/func/sub-rugby1_ses-a_task-rest_run-001_bold.nii.gz

230328-23:49:48,196 cli ERROR:
	 Preprocessing did not finish successfully. Errors occurred while processing data from participants: rugby1 (1). Check the HTML reports for details.
230328-23:49:48,196 cli ERROR:
	 Preprocessing did not finish successfully. Errors occurred while processing data from participants: rugby1 (1). Check the HTML reports for details.
230328-23:52:19,622 nipype.workflow INFO:
	 [Node] Finished "01_atropos", elapsed time 507.555654s.
230328-23:52:19,623 nipype.workflow WARNING:
	 Storing result file without outputs
230328-23:52:19,625 nipype.workflow WARNING:
	 [Node] Error on "fmriprep_22_0_wf.single_subject_rugby1_wf.anat_preproc_wf.brain_extraction_wf.atropos_wf.01_atropos" (/nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_long/work/fmriprep_22_0_wf/single_subject_rugby1_wf/anat_preproc_wf/brain_extraction_wf/atropos_wf/01_atropos)
230328-23:52:19,625 nipype.workflow WARNING:
	 Interface finished unexpectedly and the corresponding unfinished hashfile /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_long/work/fmriprep_22_0_wf/single_subject_rugby1_wf/anat_preproc_wf/brain_extraction_wf/atropos_wf/01_atropos/_0xe2a2f27b340062cb5c202893442cd177_unfinished.json does not exist. Another nipype instance may be running against the same work directory. Please ensure no other concurrent workflows are racing
exception calling callback for <Future at 0x15554423bc10 state=finished raised FileNotFoundError>
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 745, in _run_command
    _save_resultfile(
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/utils.py", line 235, in save_resultfile
    savepkl(resultsfile, result)
  File "/opt/conda/lib/python3.9/site-packages/nipype/utils/filemanip.py", line 719, in savepkl
    with pkl_open(tmpfile, "wb") as pkl_file:
  File "/opt/conda/lib/python3.9/gzip.py", line 58, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/opt/conda/lib/python3.9/gzip.py", line 173, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_long/work/fmriprep_22_0_wf/single_subject_rugby1_wf/anat_preproc_wf/brain_extraction_wf/atropos_wf/01_atropos/result_01_atropos.pklz.tmp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/plugins/multiproc.py", line 70, in run_node
    result["result"] = node.result
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 223, in result
    return _load_resultfile(
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/utils.py", line 291, in load_resultfile
    raise FileNotFoundError(results_file)
FileNotFoundError: /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_long/work/fmriprep_22_0_wf/single_subject_rugby1_wf/anat_preproc_wf/brain_extraction_wf/atropos_wf/01_atropos/result_01_atropos.pklz
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/concurrent/futures/_base.py", line 330, in _invoke_callbacks
    callback(self)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/plugins/multiproc.py", line 159, in _async_callback
    result = args.result()
  File "/opt/conda/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/opt/conda/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
FileNotFoundError: /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_long/work/fmriprep_22_0_wf/single_subject_rugby1_wf/anat_preproc_wf/brain_extraction_wf/atropos_wf/01_atropos/result_01_atropos.pklz
Sentry is attempting to send 1 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
[Wed Mar 29 12:52:21 2023]
Error in rule fmriprep:
    jobid: 0
    input: /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_long/bids/sub-rugby1/ses-a, /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_long/bids/sub-rugby1/ses-b, /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_long/bids/derivatives/freesurfer_agg/sub-rugby1
    output: /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_long/bids/derivatives/fmriprep/sub-rugby1, /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_long/bids/derivatives/fmriprep/sub-rugby1.html
    shell:
        fmriprep /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_long/bids /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_long/bids/derivatives/fmriprep participant --participant-label rugby1 --skip-bids-validation --md-only-boilerplate --fs-subjects-dir /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_long/bids/derivatives/freesurfer_agg --output-spaces MNI152NLin2009cAsym:res-2 --stop-on-first-crash --low-mem --mem-mb 25000 --nprocs 8 -w /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_long/work --fs-license-file ./license.txt
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job fmriprep since they might be corrupted:
/nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_long/bids/derivatives/fmriprep/sub-rugby1, /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_long/bids/derivatives/fmriprep/sub-rugby1.html
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
